# Generated by Django 5.2.8 on 2025-11-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.IntegerField()),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
            ],
        ),
    ]
