# Generated by Django 5.2.8 on 2025-11-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
    ]
