# Generated by Django 5.2.8 on 2025-11-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
