# Generated by Django 5.2.8 on 2025-11-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0005_alter_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comments',
            new_name='observations',
        ),
    ]
