# Generated by Django 5.2.7 on 2025-11-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='../media/signatures/'),
        ),
    ]
