# Generated by Django 5.2.8 on 2025-11-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0002_order_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('problematic', 'Problematic')], default='pending', max_length=20),
        ),
    ]
